# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3"
services:
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: Password@!
    ports:
      - "5432:5432"
    restart: always
  smartscenes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartscene_evolution
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:3000"
    restart: always
